FROM python:3.11

WORKDIR ./code
COPY . ./code

RUN pip install --no-cache-dir --upgrade -r ./code/requirements.txt
RUN pip install uvicorn
RUN pip install pytest-asyncio

CMD ["pytest", "./code/test_main.py"]